name: Deploy to Fly

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLY_APP_NAME: gamecocks-fb-bot   # MUST match fly.toml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Create app (idempotent)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -e
          flyctl apps create "$FLY_APP_NAME" || echo "App already exists"

      - name: Deploy
        id: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -e
          flyctl deploy --remote-only --app "$FLY_APP_NAME" --wait-timeout 10m

      # Always show recent app logs & status so we can see why deploy would fail
      - name: Show Fly status (always)
        if: always()
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl status -a "$FLY_APP_NAME" || true
          flyctl logs   -a "$FLY_APP_NAME" --since 15m || true

      # Kick a first collect (never fail on this)
      - name: Kick off initial collect (best effort)
        env:
          COLLECT_TOKEN_SECRET: ${{ secrets.COLLECT_TOKEN }}
        run: |
          URL="https://${{ env.FLY_APP_NAME }}.fly.dev/collect"
          if [ -n "$COLLECT_TOKEN_SECRET" ]; then
            curl -fsS -X POST -H "X-Collect-Token: $COLLECT_TOKEN_SECRET" "$URL" || true
          else
            curl -fsS -X POST "$URL" || true
          fi
