name: Deploy to Fly

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLY_APP_NAME: gamecocks-fb-bot   # MUST match app in fly.toml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      # Create the app every time (safe if it already exists)
      - name: Create app (idempotent)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -e
          flyctl apps create "$FLY_APP_NAME" || echo "App may already exist"

      # Echo apps so we can verify org/account context in logs
      - name: List apps for this token
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl apps list

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --app "$FLY_APP_NAME"

      - name: Scale web + worker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl scale count web=1 worker=1 --app "$FLY_APP_NAME"
