name: Deploy to Fly

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLY_APP_NAME: gamecocks-fb-bot
  FLY_REGION: atl

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy
        run: flyctl deploy --remote-only --app "$FLY_APP_NAME" --region "$FLY_REGION"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Ensure web + worker machines
        run: |
          flyctl scale count web=1 worker=1 --app "$FLY_APP_NAME"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
