name: Deploy to Fly (simple)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  FLY_APP_NAME: "gamecocks-fb-bot"   # must match fly.toml

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Verify FLY_API_TOKEN secret exists
        run: |
          if [ -z "${{ secrets.FLY_API_TOKEN }}" ]; then
            echo "::error::Missing GitHub secret FLY_API_TOKEN (Settings → Secrets and variables → Actions)"
            exit 1
          fi

      - name: Create app (idempotent)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl apps create "$FLY_APP_NAME" || echo "App already exists"

      - name: Deploy (detached)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only --app "$FLY_APP_NAME" --detach

      - name: Seed feed (best effort)
        env:
          COLLECT_TOKEN_SECRET: ${{ secrets.COLLECT_TOKEN }}
        run: |
          URL="https://${{ env.FLY_APP_NAME }}.fly.dev/collect"
          if [ -n "$COLLECT_TOKEN_SECRET" ]; then
            curl -fsS -X POST -H "X-Collect-Token: $COLLECT_TOKEN_SECRET" "$URL" || true
          else
            curl -fsS -X POST "$URL" || true
          fi
