name: Deploy to Fly (fast)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLY_APP_NAME: gamecocks-fb-bot

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Verify FLY_API_TOKEN secret exists
        run: |
          if [ -z "${{ secrets.FLY_API_TOKEN }}" ]; then
            echo "::error::Missing secret FLY_API_TOKEN"; exit 1; fi

      - name: Create app (idempotent)
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }
        run: flyctl apps create "$FLY_APP_NAME" || echo "exists"

      # 🚀 kick the rollout and return immediately
      - name: Deploy (detached)
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }
        run: flyctl deploy --remote-only --app "$FLY_APP_NAME" --detach

      # Show quick status but don't wait
      - name: Show status (non-blocking)
        if: always()
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }
        run: flyctl status -a "$FLY_APP_NAME" || true

      # Seed the feed (best effort; won’t fail the job)
      - name: Kick off initial collect
        env:
          COLLECT_TOKEN_SECRET: ${{ secrets.COLLECT_TOKEN }}
        run: |
          URL="https://${{ env.FLY_APP_NAME }}.fly.dev/collect"
          if [ -n "$COLLECT_TOKEN_SECRET" ]; then
            curl -fsS -X POST -H "X-Collect-Token: $COLLECT_TOKEN_SECRET" "$URL" || true
          else
            curl -fsS -X POST "$URL" || true
          fi


